name: imminex
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^3.0.1
  country_pickers: ^2.0.0
  otp_text_field: ^1.1.3
  smooth_page_indicator: ^1.0.0+2
  flutter_image_slideshow: ^0.1.2
  faker: ^2.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies: 
  flutter_lints: ^2.0.1
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/mobile/
    - assets/icons/
    - assets/web/images/

    

